package com.payasia.dao.bean;

import javax.annotation.Generated;
import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2016-08-05T15:01:33.802+0530")
@StaticMetamodel(Company.class)
public class Company_ extends BaseEntity_ {
	public static volatile SingularAttribute<Company, Long> companyId;
	public static volatile SingularAttribute<Company, String> companyCode;
	public static volatile SingularAttribute<Company, String> shortCompanyCode;
	public static volatile SingularAttribute<Company, String> companyName;
	public static volatile SingularAttribute<Company, String> dateFormat;
	public static volatile SingularAttribute<Company, Integer> part;
	public static volatile SingularAttribute<Company, Boolean> auditEnable;
	public static volatile SingularAttribute<Company, String> payslipImportType;
	public static volatile SingularAttribute<Company, Boolean> active;
	public static volatile SingularAttribute<Company, Boolean> isDemoCompany;
	public static volatile SetAttribute<Company, ClaimApplication> claimApplications;
	public static volatile SetAttribute<Company, ClaimBatchMaster> claimBatchMasters;
	public static volatile SetAttribute<Company, ClaimCategoryMaster> claimCategoryMasters;
	public static volatile SetAttribute<Company, ClaimItemMaster> claimItemMasters;
	public static volatile SetAttribute<Company, ClaimTemplate> claimTemplates;
	public static volatile SingularAttribute<Company, CompanyGroup> companyGroup;
	public static volatile SingularAttribute<Company, CountryMaster> countryMaster;
	public static volatile SingularAttribute<Company, CurrencyMaster> currencyMaster;
	public static volatile SingularAttribute<Company, FinancialYearMaster> financialYearMaster;
	public static volatile SingularAttribute<Company, PayslipFrequency> payslipFrequency;
	public static volatile SingularAttribute<Company, TimeZoneMaster> timeZoneMaster;
	public static volatile SetAttribute<Company, CompanyDocument> companyDocuments;
	public static volatile SetAttribute<Company, CompanyExchangeRate> companyExchangeRates;
	public static volatile SetAttribute<Company, CompanyExternalLink> companyExternalLinks;
	public static volatile SetAttribute<Company, CompanyLogo> companyLogos;
	public static volatile SetAttribute<Company, DataDictionary> dataDictionaries;
	public static volatile SetAttribute<Company, DataImportHistory> dataImportHistories;
	public static volatile SetAttribute<Company, DynamicForm> dynamicForms;
	public static volatile SetAttribute<Company, EmailPreferenceMaster> emailPreferenceMasters;
	public static volatile SetAttribute<Company, EmailTemplate> emailTemplates;
	public static volatile SetAttribute<Company, EmpDataExportTemplate> empDataExportTemplates;
	public static volatile SetAttribute<Company, EmpDataImportTemplate> empDataImportTemplates;
	public static volatile SetAttribute<Company, EmpNoSeriesMaster> empNoSeriesMasters;
	public static volatile SetAttribute<Company, Employee> employees;
	public static volatile SetAttribute<Company, EmployeePreferenceMaster> employeePreferenceMasters;
	public static volatile SetAttribute<Company, EmployeeRoleMapping> employeeRoleMappings;
	public static volatile SetAttribute<Company, EmployeeTypeMaster> employeeTypeMasters;
	public static volatile SetAttribute<Company, EntityListView> entityListViews;
	public static volatile SetAttribute<Company, HRLetter> hrLetters;
	public static volatile SetAttribute<Company, CompanyHolidayCalendar> companyHolidayCalendars;
	public static volatile SetAttribute<Company, LeaveApplication> leaveApplications;
	public static volatile SetAttribute<Company, LeaveBatchMaster> leaveBatchMasters;
	public static volatile SetAttribute<Company, LeaveScheme> leaveSchemes;
	public static volatile SetAttribute<Company, LeaveTypeMaster> leaveTypeMasters;
	public static volatile SetAttribute<Company, OTApplication> otApplications;
	public static volatile SetAttribute<Company, OTBatchMaster> otBatchMasters;
	public static volatile SetAttribute<Company, OTItemMaster> otItemMasters;
	public static volatile SetAttribute<Company, OTTemplate> otTemplates;
	public static volatile SetAttribute<Company, PasswordPolicyConfigMaster> passwordPolicyConfigMasters;
	public static volatile SetAttribute<Company, PasswordSecurityQuestionMaster> passwordSecurityQuestionMasters;
	public static volatile SetAttribute<Company, PayDataCollection> payDataCollections;
	public static volatile SetAttribute<Company, Paycode> paycodes;
	public static volatile SetAttribute<Company, Payslip> payslips;
	public static volatile SetAttribute<Company, ReportMaster> reportMasters;
	public static volatile SetAttribute<Company, RoleMaster> roleMasters;
	public static volatile SetAttribute<Company, WorkflowDelegate> workflowDelegates;
	public static volatile SetAttribute<Company, PayslipUploadHistory> payslipUploadHistories;
	public static volatile SetAttribute<Company, Announcement> announcements;
	public static volatile SetAttribute<Company, CompanyModuleMapping> companyModuleMappings;
	public static volatile SetAttribute<Company, CalendarCodeMaster> calendarCodeMasters;
	public static volatile SetAttribute<Company, CalendarPatternMaster> calendarPatternMasters;
	public static volatile SetAttribute<Company, CompanyCalendarTemplate> companyCalendarTemplate;
	public static volatile SetAttribute<Company, ReminderEventConfig> reminderEventConfigs;
	public static volatile SetAttribute<Company, LeaveGrantBatch> leaveGrantBatchs;
	public static volatile SetAttribute<Company, Email> emails;
	public static volatile SetAttribute<Company, LeavePreference> leavePreferences;
	public static volatile SetAttribute<Company, SchedulerStatus> schedulerStatuses;
	public static volatile SetAttribute<Company, LeaveYearEndBatch> leaveYearEndBatchs;
	public static volatile SetAttribute<Company, ClaimPreference> claimPreferences;
	public static volatile SetAttribute<Company, CompanyPayslipRelease> companyPayslipReleases;
	public static volatile SetAttribute<Company, EmployeeRoleSectionMapping> employeeRoleSectionMappings;
	public static volatile SetAttribute<Company, YearEndProcessSchedule> yearEndProcessSchedules;
}
