package com.payasia.common.util;

public class PayAsiaPrivilegeConstant {
	
	
	/* Claim Related Privileges Start */
				/* Admin Start */
	public static final String CLAIM_PREFERENCE ="hasRole('PRIV_CLAIM_PREFERENCE')";
	
				/* Admin End */
	/* Claim Related Privileges End*/
	
	
	public static final String PAY_SLIP_FORM_DESIGNER ="hasRole('PRIV_PAY_SLIP_FORM_DESIGNER')";
	public static final String CONTACT_US ="hasRole('PRIV_CONTACT_US')";
	public static final String HR_LETTERS ="hasRole('PRIV_HR_LETTERS')";
	public static final String PAY_DATA_COLLECTION ="hasRole('PRIV_PAY_DATA_COLLECTION')";
	public static final String COMPANY_INFORMATION ="hasRole('PRIV_COMPANY_INFORMATION')";
	public static final String COMPANY_FORM_DESIGNER ="hasRole('PRIV_COMPANY_FORM_DESIGNER')";
	public static final String CURRENCY_DEFINITION ="hasRole('PRIV_CURRENCY_DEFINITION')";
	public static final String LOGO_UPLOAD ="hasRole('PRIV_LOGO_UPLOAD')";
	public static final String COMPANY_DOCUMENT_CENTER ="hasRole('PRIV_COMPANY_DOCUMENT_CENTER')";
	public static final String SWITCH_COMPANY ="hasRole('PRIV_SWITCH_COMPANY')";
	public static final String EMPLOYEE_LIST ="hasRole('PRIV_EMPLOYEE_LIST')";
	public static final String EMPLOYEE_SELF_SERVICE ="hasRole('PRIV_EMPLOYEE_SELF_SERVICE')";
	public static final String EMPLOYEE_PAY_SLIP ="hasRole('PRIV_EMPLOYEE_PAY_SLIP')";
	public static final String TAX_DOCUMENT ="hasRole('PRIV_TAX_DOCUMENT')";
	public static final String IMPORT ="hasRole('PRIV_IMPORT')";
	public static final String EXPORT ="hasRole('PRIV_EXPORT')";
	public static final String EMPLOYEE_NUMBER_SERIES ="hasRole('PRIV_EMPLOYEE_NUMBER_SERIES')";
	public static final String PAY_SLIP_DESIGNER ="hasRole('PRIV_PAY_SLIP_DESIGNER')";
	public static final String CLAIM_TYPE_DEFINITION ="hasRole('PRIV_CLAIM_TYPE_DEFINITION')";
	public static final String CLAIM_TEMPLATE_DEFINITION ="hasRole('PRIV_CLAIM_TEMPLATE_DEFINITION')";
	public static final String CLAIM_REVIEWER ="hasRole('PRIV_CLAIM_REVIEWER')";
	public static final String CLAIM_BATCH_DEFINITION ="hasRole('PRIV_CLAIM_BATCH_DEFINITION')";
	public static final String ADD_CLAIMS ="hasRole('PRIV_ADD_CLAIMS')";
	public static final String MODIFY_CLAIMS ="hasRole('PRIV_MODIFY_CLAIMS')";
	public static final String WITHDRAW_CLAIMS ="hasRole('PRIV_WITHDRAW_CLAIMS')";
	public static final String LEAVE_TYPE_DEFINITION ="hasRole('PRIV_LEAVE_TYPE_DEFINITION')";
	public static final String LEAVE_SCHEME_DEFINITION ="hasRole('PRIV_LEAVE_SCHEME_DEFINITION')";
	public static final String LEAVE_TYPE_REVIEWER ="hasRole('PRIV_LEAVE_TYPE_REVIEWER')";
	public static final String LEAVE_BATCH_DEFINITION ="hasRole('PRIV_LEAVE_BATCH_DEFINITION')";
	public static final String YEAR_END_PROCESSING ="hasRole('PRIV_YEAR_END_PROCESSING')";
	public static final String ADD_LEAVES ="hasRole('PRIV_ADD_LEAVES')";
	public static final String MODIFY_LEAVES ="hasRole('PRIV_MODIFY_LEAVES')";
	public static final String WITHDRAW_LEAVES ="hasRole('PRIV_WITHDRAW_LEAVES')";
	public static final String OT_TYPE_DEFINITION ="hasRole('PRIV_OT_TYPE_DEFINITION')";
	public static final String OT_TEMPLATE_DEFINITION ="hasRole('PRIV_OT_TEMPLATE_DEFINITION')";
	public static final String OT_REVIEWER ="hasRole('PRIV_OT_REVIEWER')";
	public static final String OT_BATCH_DEFINITION ="hasRole('PRIV_OT_BATCH_DEFINITION')";
	public static final String ADD_OT ="hasRole('PRIV_ADD_OT')";
	public static final String MODIFY_OT ="hasRole('PRIV_MODIFY_OT')";
	public static final String WITHDRAW_OT ="hasRole('PRIV_WITHDRAW_OT')";
	public static final String DATA_IMPORT ="hasRole('PRIV_DATA_IMPORT')";
	public static final String DATA_EXPORT ="hasRole('PRIV_DATA_EXPORT')";
	public static final String PAYSLIP_IMPORT ="hasRole('PRIV_PAYSLIP_IMPORT')";
	public static final String MANAGE_ROLES ="hasRole('PRIV_MANAGE_ROLES')";
	public static final String ACCESS_CONTROL ="hasRole('PRIV_ACCESS_CONTROL')";
	public static final String CHANGE_EMPLOYEE_NUMBER ="hasRole('PRIV_CHANGE_EMPLOYEE_NUMBER')";
	public static final String EMAIL_TEMPLATE ="hasRole('PRIV_EMAIL_TEMPLATE')";
	public static final String SYSTEM_SWITCH_ROLE ="hasRole('PRIV_SYSTEM_SWITCH_ROLE')";
	public static final String SYSTEM_WORKFLOW_DELEGATES ="hasRole('PRIV_SYSTEM_WORKFLOW_DELEGATES')";
	public static final String HOLIDAY_LIST_DEFINITION ="hasRole('PRIV_HOLIDAY_LIST_DEFINITION')";
	public static final String HOLIDAY_LIST_MASTER ="hasRole('PRIV_HOLIDAY_LIST_MASTER')";
	public static final String EMAIL ="hasRole('PRIV_EMAIL')";
	public static final String EMPLOYEE ="hasRole('PRIV_EMPLOYEE')";
	public static final String CLAIMS_OPTIONS ="hasRole('PRIV_CLAIMS_OPTIONS')";
	public static final String REPORTING_OPTIONS ="hasRole('PRIV_REPORTING_OPTIONS')";
	public static final String PASSWORD_POLICY ="hasRole('PRIV_PASSWORD_POLICY')";
	public static final String PENDING_ITEMS ="hasRole('PRIV_PENDING_ITEMS')";
	public static final String MY_REQUESTS ="hasRole('PRIV_MY_REQUESTS')";
	public static final String CHANGE_PASSWORD ="hasRole('PRIV_CHANGE_PASSWORD')";
	public static final String MY_PROFILE ="hasRole('PRIV_MY_PROFILE')";
	public static final String MY_BALANCES ="hasRole('PRIV_MY_BALANCES')";
	public static final String TASKS_WORKFLOW_DELEGATES ="hasRole('PRIV_TASKS_WORKFLOW_DELEGATES')";
	public static final String INFO_PAY_SLIP ="hasRole('PRIV_INFO_PAY_SLIP')";
	public static final String INFO_DOCUMENT_CENTER ="hasRole('PRIV_INFO_DOCUMENT_CENTER')";
	public static final String INFO_SWITCH_ROLE ="hasRole('PRIV_INFO_SWITCH_ROLE')";
	public static final String EMPLOYEE_FORM_DESIGNER ="hasRole('PRIV_EMPLOYEE_FORM_DESIGNER')";
	public static final String MULTILINGUAL ="hasRole('PRIV_MULTILINGUAL')";
	public static final String EXTERNAL_LINK ="hasRole('PRIV_EXTERNAL_LINK')";
	public static final String CALENDAR_TEMPLATE_DEFINITION ="hasRole('PRIV_CALENDAR_TEMPLATE_DEFINITION')";
	public static final String EMPLOYEE_CALENDAR_DEFINITION ="hasRole('PRIV_EMPLOYEE_CALENDAR_DEFINITION')";
	public static final String ASSIGN_LEAVE_SCHEME ="hasRole('PRIV_ASSIGN_LEAVE_SCHEME')";
	public static final String LEAVE_BALANCE_SUMMARY ="hasRole('PRIV_LEAVE BALANCE SUMMARY')";
	public static final String EMPLOYEE_LEAVE_BALANCE_SUMMARY ="hasRole('PRIV_EMPLOYEE_LEAVE_BALANCE_SUMMARY')";
	public static final String LEAVE_GRANTER ="hasRole('PRIV_LEAVE_GRANTER')";
	public static final String LEAVE_EVENT_REMINDER ="hasRole('PRIV_LEAVE_EVENT_REMINDER')";
	public static final String LEAVE_PREFERENCE ="hasRole('PRIV_LEAVE_PREFERENCE')";
	public static final String LEAVE_REPORTS ="hasRole('PRIV_LEAVE_REPORTS')";
	public static final String PAYSLIP_RELEASE ="hasRole('PRIV_PAYSLIP_RELEASE')";
	public static final String ASSIGN_CLAIM_TEMPLATE ="hasRole('PRIV_ASSIGN_CLAIM_TEMPLATE')";
	public static final String PENDING_CLAIM ="hasRole('PRIV_PENDING_CLAIM')";
	public static final String MY_CLAIM ="hasRole('PRIV_MY_CLAIM')";
	
	public static final String EMPLOYEE_CLAIMS ="hasRole('PRIV_EMPLOYEE_CLAIMS')";
	public static final String CLAIM_REPORTS ="hasRole('PRIV_CLAIM_REPORTS')";
	public static final String LEAVE_REVIEW ="hasRole('PRIV_LEAVE_REVIEW')";
	public static final String MANAGER_LEAVE_REPORTS ="hasRole('PRIV_MANAGER_LEAVE_REPORTS')";
	public static final String HRIS_REVIEWER ="hasRole('PRIV_HRIS_REVIEWER')";
	public static final String INFO_HR_LETTERS ="hasRole('PRIV_INFO_HR_LETTERS')";
	public static final String HRIS_PREFERENCE ="hasRole('PRIV_HRIS_PREFERENCE')";
	public static final String HRIS_MY_REQUEST ="hasRole('PRIV_HRIS_MY_REQUEST')";
	public static final String HRIS_PENDING_ITEMS ="hasRole('PRIV_HRIS_PENDING_ITEMS')";
	public static final String EMPLOYEE_CLAIM_SUMMARY ="hasRole('PRIV_EMPLOYEE_CLAIM_SUMMARY')";
	public static final String EMPLOYEE_ENTITLEMENTS ="hasRole('PRIV_EMPLOYEE_ENTITLEMENTS')";
	public static final String LUNDIN_PENDING_TIMESHEET ="hasRole('PRIV_LUNDIN_PENDING_TIMESHEET')";
	public static final String LUNDIN_TIMESHEET ="hasRole('PRIV_LUNDIN_TIMESHEET')";
	public static final String LUNDIN_AFE ="hasRole('PRIV_LUNDIN_AFE')";
	public static final String LUNDIN_BLOCK ="hasRole('PRIV_LUNDIN_BLOCK')";
	public static final String LUNDIN_DEPARTMENT ="hasRole('PRIV_LUNDIN_DEPARTMENT')";
	public static final String LUNDIN_TIMESHEET_PREFERENCE ="hasRole('PRIV_LUNDIN_TIMESHEET_PREFERENCE')";
	public static final String LUNDIN_TIMESHEET_REVIEWER ="hasRole('PRIV_LUNDIN_TIMESHEET_REVIEWER')";
	public static final String LUNDIN_TIMESHEET_REPORT ="hasRole('PRIV_LUNDIN_TIMESHEET_REPORT')";
	public static final String LUNDIN_TIMESHEET_EVENT_REMINDER ="hasRole('PRIV_LUNDIN_TIMESHEET_EVENT_REMINDER')";
	public static final String HRIS_REPORTS ="hasRole('PRIV_HRIS_REPORTS')";
	public static final String DISCUSSION_BOARD ="hasRole('PRIV_DISCUSSION_BOARD')";
	public static final String MANAGE_MODULE ="hasRole('PRIV_MANAGE_MODULE')";
	public static final String LION_TIMESHEET ="hasRole('PRIV_LION_TIMESHEET')";
	public static final String LION_EMPLOYEE_TIMESHEET ="hasRole('PRIV_LION_EMPLOYEE_TIMESHEET')";
	public static final String MANAGER_LION_TIMESHEET_REPORT ="hasRole('PRIV_MANAGER_LION_TIMESHEET_REPORT')";
	public static final String LION_ADMIN_EMPLOYEE_TIMESHEET ="hasRole('PRIV_LION_ADMIN_EMPLOYEE_TIMESHEET')";
	public static final String ADMIN_LION_TIMESHEET_REPORT ="hasRole('PRIV_ADMIN_LION_TIMESHEET_REPORT')";
	public static final String LION_TIMESHEET_PREFERENCE ="hasRole('PRIV_LION_TIMESHEET_PREFERENCE')";
	public static final String LION_TIMESHEET_REVIEWER ="hasRole('PRIV_LION_TIMESHEET_REVIEWER')";
	public static final String LION_TIMESHEET_EVENT_REMINDER ="hasRole('PRIV_LION_TIMESHEET_EVENT_REMINDER')";
	public static final String COHERENT_MY_OVERTIME_TIMESHEET ="hasRole('PRIV_COHERENT_MY_OVERTIME_TIMESHEET')";
	public static final String COHERENT_EMPLOYEE_OVERTIME ="hasRole('PRIV_COHERENT_EMPLOYEE_OVERTIME')";
	public static final String COHERENT_ADMIN_EMPLOYEE_OVERTIME ="hasRole('PRIV_COHERENT_ADMIN_EMPLOYEE_OVERTIME')";
	public static final String COHERENT_MY_SHIFT_TIMESHEET ="hasRole('PRIV_COHERENT_MY_SHIFT_TIMESHEET')";
	public static final String COHERENT_EMPLOYEE_SHIFT ="hasRole('PRIV_COHERENT_EMPLOYEE_SHIFT')";
	public static final String COHERENT_ADMIN_EMPLOYEE_SHIFT ="hasRole('PRIV_COHERENT_ADMIN_EMPLOYEE_SHIFT')";
	public static final String MANAGER_COHERENT_TIMESHEET_REPORT ="hasRole('PRIV_MANAGER_COHERENT_TIMESHEET_REPORT')";
	public static final String ADMIN_COHERENT_TIMESHEET_REPORT ="hasRole('PRIV_ADMIN_COHERENT_TIMESHEET_REPORT')";
	public static final String COHERENT_TIMESHEET_PREFERENCE ="hasRole('PRIV_COHERENT_TIMESHEET_PREFERENCE')";
	public static final String COHERENT_TIMESHEET_REVIEWER ="hasRole('PRIV_COHERENT_TIMESHEET_REVIEWER')";
	public static final String COHERENT_TIMESHEET_EVENT_REMINDER ="hasRole('PRIV_COHERENT_TIMESHEET_EVENT_REMINDER')";
	public static final String MANAGER_LUNDIN_TIMESHEET_REPORT ="hasRole('PRIV_MANAGER_LUNDIN_TIMESHEET_REPORT')";
	public static final String PayAsia_MY_OVERTIME_TIMESHEET ="hasRole('PRIV_PayAsia_MY_OVERTIME_TIMESHEET')";
	public static final String PayAsia_EMPLOYEE_OVERTIME ="hasRole('PRIV_PayAsia_EMPLOYEE_OVERTIME')";
	public static final String PayAsia_MY_SHIFT_TIMESHEET ="hasRole('PRIV_PayAsia_MY_SHIFT_TIMESHEET')";
	public static final String PayAsia_EMPLOYEE_SHIFT ="hasRole('PRIV_PayAsia_EMPLOYEE_SHIFT')";
	public static final String MANAGER_PayAsia_TIMESHEET_REPORT ="hasRole('PRIV_MANAGER_PayAsia_TIMESHEET_REPORT')";
	public static final String PayAsia_ADMIN_EMPLOYEE_OVERTIME ="hasRole('PRIV_PayAsia_ADMIN_EMPLOYEE_OVERTIME')";
	public static final String PayAsia_ADMIN_EMPLOYEE_SHIFT ="hasRole('PRIV_PayAsia_ADMIN_EMPLOYEE_SHIFT')";
	public static final String ADMIN_PayAsia_TIMESHEET_REPORT ="hasRole('PRIV_ADMIN_PayAsia_TIMESHEET_REPORT')";
	public static final String PayAsia_TIMESHEET_PREFERENCE ="hasRole('PRIV_PayAsia_TIMESHEET_PREFERENCE')";
	public static final String PayAsia_TIMESHEET_REVIEWER ="hasRole('PRIV_PayAsia_TIMESHEET_REVIEWER')";
	public static final String PayAsia_TIMESHEET_EVENT_REMINDER ="hasRole('PRIV_PayAsia_TIMESHEET_EVENT_REMINDER')";
	public static final String EMPLOYEE_ITEM_ENTITLEMENTS ="hasRole('PRIV_EMPLOYEE_ITEM_ENTITLEMENTS')";
	public static final String MANAGER_CLAIM_REPORTS ="hasRole('PRIV_MANAGER_CLAIM_REPORTS')";

}
